wiki_creds:
  development:
    user_agent: 'WikiEduWizard/1.0 (http://wikiedu.org/WikiEduWizard/; kevin@wintr.us) WikiEduWizard/1.0'
    url: "http://test2.wikipedia.org/w/api.php"
    key: '[WIKIMEDIA API KEY]'
    secret: '[WIKIMEDIA API SECRET]'
  production:
    user_agent: 'WikiEduWizard/1.0 (http://wikiedu.org/WikiEduWizard/; kevin@wintr.us) WikiEduWizard/1.0'
    url: "http://en.wikipedia.org/w/api.php"
    key: '[WIKIMEDIA API KEY]'
    secret: '[WIKIMEDIA API SECRET]'